-- MySQL Script generated by MySQL Workbench
-- Sun Nov 24 14:34:05 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SUSTechBus
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SUSTechBus
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SUSTechBus` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `SUSTechBus` ;

-- -----------------------------------------------------
-- Table `SUSTechBus`.`Lines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SUSTechBus`.`Lines` (
  `id` INT NOT NULL,
  `start` INT NOT NULL COMMENT 'start stop\n',
  `end` INT NOT NULL COMMENT 'end stop',
  `name` VARCHAR(45) NOT NULL COMMENT 'name or description',
  `type` VARCHAR(45) NOT NULL DEFAULT 'normal' COMMENT 'normal, peak or iPARK line',
  `modifyTime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_l_terminations_start`
    FOREIGN KEY (`start`)
    REFERENCES `SUSTechBus`.`Stops` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_l_terminations_end`
    FOREIGN KEY (`end`)
    REFERENCES `SUSTechBus`.`Stops` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `SUSTechBus`.`Lines` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_l_ss_idx` ON `SUSTechBus`.`Lines` (`start` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_l_terminations_end_idx` ON `SUSTechBus`.`Lines` (`end` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `SUSTechBus`.`RecordLine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SUSTechBus`.`RecordLine` (
  `id` INT NOT NULL,
  `startTime` TIMESTAMP NOT NULL,
  `logTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `weekend` INT NOT NULL DEFAULT 0 COMMENT 'weekend or not, should be 0 or 1',
  `line` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_rl_line`
    FOREIGN KEY (`id`)
    REFERENCES `SUSTechBus`.`Lines` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `SUSTechBus`.`RecordLine` (`id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `SUSTechBus`.`RecordTime`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SUSTechBus`.`RecordTime` (
  `recordLineID` INT NOT NULL,
  `stopOrd` INT NOT NULL COMMENT 'the order of the current evaluating stop',
  `duration` DECIMAL(14,4) NOT NULL COMMENT 'duration from the last stop',
  PRIMARY KEY (`recordLineID`),
  CONSTRAINT `fk_rt_recordLine`
    FOREIGN KEY (`recordLineID`)
    REFERENCES `SUSTechBus`.`RecordLine` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `rLineOrd` ON `SUSTechBus`.`RecordTime` (`recordLineID` ASC, `stopOrd` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `SUSTechBus`.`Stops`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SUSTechBus`.`Stops` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL COMMENT 'Name and Description of the bus stopt',
  `modifyTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `longitude` DECIMAL(14,4) NOT NULL,
  `latitude` DECIMAL(14,4) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `SUSTechBus`.`Stops` (`id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `SUSTechBus`.`StopsInLine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SUSTechBus`.`StopsInLine` (
  `line` INT NOT NULL,
  `stop` INT NOT NULL,
  `ord` INT NOT NULL,
  `modifyTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT `fk_sil_line`
    FOREIGN KEY (`line`)
    REFERENCES `SUSTechBus`.`Lines` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sil_stop`
    FOREIGN KEY (`stop`)
    REFERENCES `SUSTechBus`.`Stops` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `lineOrd` ON `SUSTechBus`.`StopsInLine` (`line` ASC, `ord` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_stop_idx` ON `SUSTechBus`.`StopsInLine` (`stop` ASC) VISIBLE;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
