==== Time Schedule ====

================

[SCHEDULE 1] Start time 0:7.
[STATION 0] Wait 7 minutes.
[STATION 6] Wait 1 minutes.
[STATION 12] Wait 0 minutes.

================

[SCHEDULE 2] Start time 0:9.
[STATION 0] Wait 9 minutes.
[STATION 4] Wait 0 minutes.
[STATION 5] Wait 1 minutes.
[STATION 6] Wait 1 minutes.
[STATION 12] Wait 0 minutes.

================

[SCHEDULE 3] Start time 0:9.
[STATION 0] Wait 9 minutes.
[STATION 4] Wait 0 minutes.
[STATION 6] Wait 0 minutes.
[STATION 7] Wait 0 minutes.
[STATION 8] Wait 0 minutes.
[STATION 10] Wait 0 minutes.
[STATION 11] Wait 0 minutes.
[STATION 12] Wait 0 minutes.

================

[SCHEDULE 4] Start time 0:8.
[STATION 0] Wait 8 minutes.
[STATION 3] Wait 1 minutes.
[STATION 6] Wait 1 minutes.
[STATION 12] Wait 8 minutes.

================

[SCHEDULE 5] Start time 0:7.
[STATION 0] Wait 8 minutes.
[STATION 3] Wait 0 minutes.
[STATION 4] Wait 0 minutes.
[STATION 6] Wait 0 minutes.
[STATION 7] Wait 0 minutes.
[STATION 8] Wait 0 minutes.
[STATION 10] Wait 0 minutes.
[STATION 11] Wait 0 minutes.
[STATION 12] Wait 0 minutes.

================

[SCHEDULE 6] Start time 0:7.
[STATION 0] Wait 7 minutes.
[STATION 4] Wait 1 minutes.
[STATION 6] Wait 3 minutes.
[STATION 7] Wait 0 minutes.
[STATION 8] Wait 0 minutes.
[STATION 10] Wait 0 minutes.
[STATION 11] Wait 0 minutes.
[STATION 12] Wait 0 minutes.

================

[SCHEDULE 7] Start time 0:6.
[STATION 0] Wait 6 minutes.
[STATION 4] Wait 0 minutes.
[STATION 5] Wait 0 minutes.
[STATION 6] Wait 1 minutes.
[STATION 7] Wait 0 minutes.
[STATION 8] Wait 0 minutes.
[STATION 10] Wait 0 minutes.
[STATION 11] Wait 0 minutes.
[STATION 12] Wait 0 minutes.

================

[SCHEDULE 8] Start time 0:4.
[STATION 0] Wait 4 minutes.
[STATION 2] Wait 0 minutes.
[STATION 3] Wait 0 minutes.
[STATION 4] Wait 0 minutes.
[STATION 6] Wait 0 minutes.
[STATION 7] Wait 0 minutes.
[STATION 8] Wait 0 minutes.
[STATION 10] Wait 3 minutes.
[STATION 11] Wait 0 minutes.
[STATION 12] Wait 0 minutes.

================

[SCHEDULE 9] Start time 0:5.
[STATION 0] Wait 5 minutes.
[STATION 4] Wait 0 minutes.
[STATION 6] Wait 0 minutes.
[STATION 7] Wait 0 minutes.
[STATION 8] Wait 0 minutes.
[STATION 10] Wait 0 minutes.
[STATION 11] Wait 0 minutes.
[STATION 12] Wait 0 minutes.

================

[SCHEDULE 10] Start time 0:4.
[STATION 0] Wait 4 minutes.
[STATION 6] Wait 1 minutes.
[STATION 12] Wait 0 minutes.

================

[SCHEDULE 11] Start time 0:5.
[STATION 0] Wait 6 minutes.
[STATION 3] Wait 0 minutes.
[STATION 6] Wait 1 minutes.
[STATION 12] Wait 0 minutes.

================

[SCHEDULE 12] Start time 0:2.
[STATION 0] Wait 2 minutes.
[STATION 2] Wait 0 minutes.
[STATION 3] Wait 0 minutes.
[STATION 4] Wait 0 minutes.
[STATION 6] Wait 0 minutes.
[STATION 7] Wait 0 minutes.
[STATION 8] Wait 1 minutes.
[STATION 10] Wait 0 minutes.
[STATION 11] Wait 0 minutes.
[STATION 12] Wait 0 minutes.

================

[SCHEDULE 13] Start time 0:1.
[STATION 0] Wait 1 minutes.
[STATION 6] Wait 0 minutes.
[STATION 7] Wait 0 minutes.
[STATION 8] Wait 0 minutes.
[STATION 10] Wait 0 minutes.
[STATION 11] Wait 0 minutes.
[STATION 12] Wait 0 minutes.

================

[SCHEDULE 14] Start time 0:1.
[STATION 0] Wait 2 minutes.
[STATION 3] Wait 0 minutes.
[STATION 4] Wait 0 minutes.
[STATION 5] Wait 0 minutes.
[STATION 6] Wait 1 minutes.
[STATION 12] Wait 0 minutes.

================

[SCHEDULE 15] Start time 0:3.
[STATION 0] Wait 4 minutes.
[STATION 3] Wait 1 minutes.
[STATION 4] Wait 0 minutes.
[STATION 6] Wait 1 minutes.
[STATION 12] Wait 0 minutes.

================

[SCHEDULE 16] Start time 0:10.
[STATION 0] Wait 10 minutes.
[STATION 6] Wait 1 minutes.
[STATION 12] Wait 0 minutes.

================

[SCHEDULE 17] Start time 0:14.
[STATION 0] Wait 14 minutes.
[STATION 4] Wait 0 minutes.
[STATION 6] Wait 1 minutes.
[STATION 12] Wait 0 minutes.

================

[SCHEDULE 18] Start time 0:15.
[STATION 0] Wait 15 minutes.
[STATION 4] Wait 0 minutes.
[STATION 6] Wait 0 minutes.
[STATION 7] Wait 0 minutes.
[STATION 8] Wait 0 minutes.
[STATION 10] Wait 0 minutes.
[STATION 11] Wait 0 minutes.
[STATION 12] Wait 0 minutes.

================

[SCHEDULE 19] Start time 0:14.
[STATION 0] Wait 14 minutes.
[STATION 3] Wait 3 minutes.
[STATION 6] Wait 0 minutes.
[STATION 9] Wait 4 minutes.
[STATION 10] Wait 0 minutes.
[STATION 11] Wait 0 minutes.
[STATION 12] Wait 0 minutes.

================

[SCHEDULE 20] Start time 0:14.
[STATION 0] Wait 14 minutes.
[STATION 4] Wait 0 minutes.
[STATION 5] Wait 0 minutes.
[STATION 6] Wait 0 minutes.
[STATION 7] Wait 0 minutes.
[STATION 8] Wait 0 minutes.
[STATION 10] Wait 0 minutes.
[STATION 11] Wait 2 minutes.
[STATION 12] Wait 0 minutes.

================

[SCHEDULE 21] Start time 0:13.
[STATION 0] Wait 13 minutes.
[STATION 4] Wait 0 minutes.
[STATION 5] Wait 0 minutes.
[STATION 6] Wait 2 minutes.
[STATION 7] Wait 0 minutes.
[STATION 8] Wait 0 minutes.
[STATION 10] Wait 0 minutes.
[STATION 11] Wait 0 minutes.
[STATION 12] Wait 3 minutes.

================

[SCHEDULE 22] Start time 0:12.
[STATION 0] Wait 12 minutes.
[STATION 4] Wait 0 minutes.
[STATION 6] Wait 0 minutes.
[STATION 9] Wait 3 minutes.
[STATION 10] Wait 0 minutes.
[STATION 11] Wait 0 minutes.
[STATION 12] Wait 0 minutes.

================

[SCHEDULE 23] Start time 0:11.
[STATION 0] Wait 12 minutes.
[STATION 3] Wait 0 minutes.
[STATION 4] Wait 0 minutes.
[STATION 6] Wait 0 minutes.
[STATION 7] Wait 0 minutes.
[STATION 8] Wait 0 minutes.
[STATION 10] Wait 0 minutes.
[STATION 11] Wait 0 minutes.
[STATION 12] Wait 0 minutes.

================

[SCHEDULE 24] Start time 0:10.
[STATION 0] Wait 10 minutes.
[STATION 4] Wait 0 minutes.
[STATION 5] Wait 0 minutes.
[STATION 6] Wait 0 minutes.
[STATION 9] Wait 5 minutes.
[STATION 10] Wait 0 minutes.
[STATION 11] Wait 0 minutes.
[STATION 12] Wait 0 minutes.

================

[SCHEDULE 25] Start time 0:9.
[STATION 0] Wait 9 minutes.
[STATION 4] Wait 0 minutes.
[STATION 5] Wait 0 minutes.
[STATION 6] Wait 1 minutes.
[STATION 12] Wait 0 minutes.
